workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    environment:
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli
      - name: Build iOS app
        script: |
          expo build:ios --type archive
    artifacts:
      - '*.ipa'
    publishing:
      email:
        recipients:
          - mindfulharborapp@gmail.com
